# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fasthtml',
                'doc_host': 'https://rrayanna.github.io',
                'git_url': 'https://github.com/rrayanna/fasthtml',
                'lib_path': 'fasthtml'},
  'syms': {'fasthtml.core': {'fasthtml.core.foo': ('core.html#foo', 'fasthtml/core.py')}}}
